# Generated by Django 4.2.10 on 2024-02-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_created_on_alter_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_on',
        ),
    ]
