# Generated by Django 4.2.10 on 2024-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userprofile_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(default='User.first_name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(default='User.last_name'),
        ),
    ]
