# Generated by Django 4.2.10 on 2024-02-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userprofile_fname_alter_userprofile_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
    ]
