# Generated by Django 4.2.10 on 2024-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_ln_1',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_ln_2',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_ln_3',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True),
        ),
    ]
