# Generated by Django 4.2.10 on 2024-02-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userprofile_address_ln_2_userprofile_address_ln_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='address_ln_1',
        ),
    ]
