# Generated by Django 4.2.10 on 2024-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_address_userprofile_address_ln_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_ln_3',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_ln_1',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_ln_2',
            new_name='town_city',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_number',
            field=models.CharField(blank=True, default='0'),
        ),
    ]
