# Generated by Django 4.2.10 on 2024-02-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0022_userprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradesman', '0002_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('trades_required', multiselectfield.db.fields.MultiSelectField(choices=[('Ca', 'Carpenter'), ('Pl', 'Plumber'), ('El', 'Electrician'), ('Pa', 'Plasterer'), ('Gw', 'Groundsworker'), ('De', 'Decorator'), ('Ga', 'Gas'), ('AD', 'Planner')], max_length=30)),
                ('job_number', models.IntegerField()),
                ('phone', models.CharField(blank=True)),
                ('other_phone', models.CharField(blank=True, verbose_name='Other Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(blank=True)),
                ('town_city', models.CharField(blank=True, verbose_name='Town/City')),
                ('county', models.CharField(blank=True)),
                ('postcode', models.CharField(blank=True)),
                ('job_description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Pending Start'), (2, 'In progress'), (3, 'Completed')], verbose_name='Job Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tradesman_assigned', models.ManyToManyField(to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradesman.job')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradesman.task')),
            ],
        ),
    ]
