# Generated by Django 4.2.10 on 2024-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesman', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_name',
            field=models.CharField(default='[Name]', max_length=30),
        ),
    ]
