# Generated by Django 4.2.10 on 2024-02-27 20:17

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_userprofile_profile_image'),
        ('tradesman', '0008_remove_task_tradesman_assigned_delete_jobtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('trades_required', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ca', 'Carpenter'), ('Pl', 'Plumber'), ('El', 'Electrician'), ('Pa', 'Plasterer'), ('Gw', 'Groundsworker'), ('De', 'Decorator'), ('Ga', 'Gas'), ('AD', 'Planner')], max_length=30)),
                ('time_required', models.CharField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='tradesman.job')),
                ('tradesman_assigned', models.ManyToManyField(blank=True, to='main.userprofile')),
            ],
        ),
    ]
