# Generated by Django 4.2.10 on 2024-09-10 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('job_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('other_phone', models.CharField(blank=True, max_length=15, verbose_name='Other Phone Number')),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=40)),
                ('town_city', models.CharField(blank=True, max_length=20, verbose_name='Town/City')),
                ('county', models.CharField(blank=True, max_length=25)),
                ('postcode', models.CharField(max_length=10)),
                ('job_description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Pending Start'), (2, 'In Progress'), (3, 'Completed')], verbose_name='Job Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('trades_required', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ca', 'Carpenter'), ('Pl', 'Plumber'), ('El', 'Electrician'), ('Pa', 'Plasterer'), ('Gw', 'Groundsworker'), ('De', 'Decorator'), ('Ga', 'Gas'), ('AD', 'Planner')], max_length=30)),
                ('time_required', models.CharField(blank=True, max_length=25)),
                ('is_completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='tradesman.job')),
                ('tradesman_assigned', models.ManyToManyField(blank=True, related_name='tradesman', to='main.userprofile')),
            ],
            options={
                'ordering': ['is_completed'],
            },
        ),
    ]
