# Generated by Django 4.2.10 on 2024-02-26 20:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('trades_required', multiselectfield.db.fields.MultiSelectField(choices=[('Ca', 'Carpenter'), ('Pl', 'Plumber'), ('El', 'Electrician'), ('Pa', 'Plasterer'), ('Gw', 'Groundsworker'), ('De', 'Decorator'), ('Ga', 'Gas'), ('AD', 'Planner')], max_length=30)),
                ('job_number', models.IntegerField()),
                ('phone', models.CharField(blank=True)),
                ('other_phone', models.CharField(blank=True, verbose_name='Other Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(blank=True)),
                ('town_city', models.CharField(blank=True, verbose_name='Town/City')),
                ('county', models.CharField(blank=True)),
                ('postcode', models.CharField(blank=True)),
                ('job_description', models.TextField()),
                ('add_task', models.CharField()),
                ('pending_task', models.CharField()),
            ],
        ),
    ]
