# Generated by Django 4.2.10 on 2024-02-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradesman', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
