# Generated by Django 4.2.10 on 2024-02-27 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_userprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradesman', '0006_alter_job_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='trades_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tradesman_assigned',
        ),
        migrations.AddField(
            model_name='task',
            name='time_required',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='trades_required',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ca', 'Carpenter'), ('Pl', 'Plumber'), ('El', 'Electrician'), ('Pa', 'Plasterer'), ('Gw', 'Groundsworker'), ('De', 'Decorator'), ('Ga', 'Gas'), ('AD', 'Planner')], max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='tradesman_assigned',
            field=models.ManyToManyField(blank=True, to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_name',
            field=models.CharField(max_length=30),
        ),
    ]
