# Generated by Django 4.2.10 on 2024-02-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradesman', '0007_remove_job_trades_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tradesman_assigned',
        ),
        migrations.DeleteModel(
            name='JobTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
