# Generated by Django 4.2.10 on 2024-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesman', '0011_alter_job_email_alter_job_phone_alter_job_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='county',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='other_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Other Phone Number'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='street',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='town_city',
            field=models.CharField(blank=True, max_length=20, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_required',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
