# Generated by Django 4.2.10 on 2024-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(default='first name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(default='last name'),
        ),
    ]
