# Generated by Django 4.2.10 on 2024-02-24 15:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['role']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from=['fname', 'lname']),
        ),
    ]
