# Generated by Django 4.2.10 on 2024-02-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userprofile_email_userprofile_emergency_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_ln_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_ln_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_ln_3',
        ),
    ]
