# Generated by Django 4.2.10 on 2024-02-25 18:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='0', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='07123456789', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='07123456789', max_length=128, region=None),
        ),
    ]
