# Generated by Django 4.2.10 on 2024-02-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_userprofile_emergency_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_ln_2',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_ln_3',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_phone',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True),
        ),
    ]
