# Generated by Django 4.2.10 on 2024-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_userprofile_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
