# Generated by Django 4.2.10 on 2024-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_userprofile_email_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_initial_signup',
            field=models.BooleanField(default=True),
        ),
    ]
