# Generated by Django 4.2.10 on 2024-09-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_userprofile_is_initial_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nok_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Next of Kin contact number'),
        ),
    ]
